-- Zukkolab demo kontenti (statik). Dinamik qism (guruhlar, slotlar, lidlar) — select public.reset_demo_data().
-- Barcha maʼlumotlar toʻqima. Qayta ishga tushirish xavfsiz: kontent jadvallari tozalanib qayta toʻldiriladi.

begin;

delete from public.bookings; delete from public.students; delete from public.lead_events; delete from public.leads;
delete from public.test_attempts; delete from public.trial_slots; delete from public.groups;
delete from public.test_questions; delete from public.testimonials; delete from public.faq;
delete from public.teachers; delete from public.courses; delete from public.branches; delete from public.directions;

insert into public.directions (slug, name_uz, name_ru, name_en, icon, color, has_test, sort) values
  ('english', 'Ingliz tili', 'Английский язык', 'English', 'languages', '#6D4AFF', true, 1),
  ('russian', 'Rus tili', 'Русский язык', 'Russian', 'book-open', '#FF6B57', true, 2),
  ('math', 'Matematika', 'Математика', 'Mathematics', 'sigma', '#14121F', true, 3),
  ('it', 'IT va dasturlash', 'IT и программирование', 'IT and coding', 'code', '#2F9E6B', true, 4),
  ('abiturient', 'Abituriyentlar', 'Абитуриенты', 'University prep', 'graduation-cap', '#E2A400', true, 5);

insert into public.branches (slug, name_uz, name_ru, name_en, address_uz, address_ru, address_en, landmark_uz, landmark_ru, landmark_en, lat, lng, phone, working_hours_uz, working_hours_ru, working_hours_en, photo_url, sort) values
  ('chilonzor', 'Chilonzor', 'Чиланзар', 'Chilanzar', 'Chilonzor tumani, Bunyodkor shoh koʻchasi, 12-uy', 'Чиланзарский район, проспект Бунёдкор, 12', '12 Bunyodkor Avenue, Chilanzar district', 'Novza metro bekati yonida', 'Рядом со станцией метро Новза', 'Next to Novza metro station', 41.2826, 69.2125, '+998712001010', 'Du–Sh: 09:00–20:00, Ya: dam olish', 'Пн–Сб: 09:00–20:00, Вс: выходной', 'Mon–Sat: 9:00–20:00, Sun: closed', '/images/branches/chilonzor.webp', 1),
  ('yunusobod', 'Yunusobod', 'Юнусабад', 'Yunusabad', 'Yunusobod tumani, Amir Temur shoh koʻchasi, 108-uy', 'Юнусабадский район, проспект Амира Темура, 108', '108 Amir Temur Avenue, Yunusabad district', 'Yunusobod metro bekati, 3-chiqish', 'Станция метро Юнусабад, выход 3', 'Yunusabad metro station, exit 3', 41.3647, 69.287, '+998712002020', 'Du–Sh: 09:00–20:00, Ya: dam olish', 'Пн–Сб: 09:00–20:00, Вс: выходной', 'Mon–Sat: 9:00–20:00, Sun: closed', '/images/branches/yunusobod.webp', 2),
  ('mirzo-ulugbek', 'Mirzo Ulugʻbek', 'Мирзо-Улугбек', 'Mirzo Ulugbek', 'Mirzo Ulugʻbek tumani, Buyuk Ipak Yoʻli koʻchasi, 45-uy', 'Мирзо-Улугбекский район, улица Буюк Ипак Йули, 45', '45 Buyuk Ipak Yuli Street, Mirzo Ulugbek district', 'Buyuk Ipak Yoʻli metro bekati qarshisida', 'Напротив станции метро Буюк Ипак Йули', 'Opposite Buyuk Ipak Yuli metro station', 41.326, 69.327, '+998712003030', 'Du–Sh: 09:00–20:00, Ya: dam olish', 'Пн–Сб: 09:00–20:00, Вс: выходной', 'Mon–Sat: 9:00–20:00, Sun: closed', '/images/branches/mirzo-ulugbek.webp', 3);

insert into public.courses (direction_id, slug, title_uz, title_ru, title_en, description_uz, description_ru, description_en, program_uz, program_ru, program_en, level_from, level_to, age_group, duration_months, lessons_per_week, lesson_minutes, price_monthly, is_featured, sort) values
  ((select id from public.directions where slug = 'english'), 'english-kids', 'Bolalar uchun ingliz tili', 'Английский для детей', 'English for Kids', '7–11 yoshli bolalar uchun oʻyin, qoʻshiq va multfilmlar orqali ingliz tili. Har darsda gapirish amaliyoti.', 'Английский для детей 7–11 лет через игры, песни и мультфильмы. Разговорная практика на каждом уроке.', 'English for children aged 7–11 through games, songs and cartoons. Speaking practice in every lesson.', array['Alifbo va talaffuz', 'Kundalik soʻzlar: oila, maktab, hayvonlar', 'Oddiy jumlalar tuzish', 'Qoʻshiq va rolli oʻyinlar']::text[], array['Алфавит и произношение', 'Повседневные слова: семья, школа, животные', 'Простые предложения', 'Песни и ролевые игры']::text[], array['Alphabet and pronunciation', 'Everyday words: family, school, animals', 'Building simple sentences', 'Songs and role plays']::text[], 1, 2, 'kids', 9, 3, 60, 600000, false, 1),
  ((select id from public.directions where slug = 'english'), 'general-english', 'General English', 'General English', 'General English', 'Boshlangʻichdan B2 gacha: grammatika, lugʻat va erkin muloqot. Har 2 oyda daraja nazorati.', 'С нуля до B2: грамматика, лексика и свободное общение. Контроль уровня каждые 2 месяца.', 'From beginner to B2: grammar, vocabulary and fluent conversation. Level check every 2 months.', array['Grammatika asoslari', 'Soʻz boyligi: 1500+ soʻz', 'Speaking club har hafta', 'Daraja imtihoni']::text[], array['Основы грамматики', 'Словарный запас: 1500+ слов', 'Speaking club каждую неделю', 'Экзамен на уровень']::text[], array['Grammar foundations', 'Vocabulary: 1,500+ words', 'Weekly speaking club', 'Level exam']::text[], 1, 3, 'teens', 6, 3, 90, 750000, true, 2),
  ((select id from public.directions where slug = 'english'), 'ielts-intensive', 'IELTS Intensive', 'IELTS Intensive', 'IELTS Intensive', 'B1 dan boshlab IELTS 7.0+ ga tayyorlov: 4 ta koʻnikma, haftalik mock test va individual feedback.', 'Подготовка к IELTS 7.0+ с уровня B1: 4 навыка, еженедельный mock-тест и индивидуальный разбор.', 'IELTS 7.0+ preparation from B1: all 4 skills, weekly mock test and individual feedback.', array['Listening va Reading strategiyalari', 'Writing Task 1 va 2', 'Speaking: Part 1–3', 'Har hafta mock test']::text[], array['Стратегии Listening и Reading', 'Writing Task 1 и 2', 'Speaking: Part 1–3', 'Mock-тест каждую неделю']::text[], array['Listening and Reading strategies', 'Writing Task 1 and 2', 'Speaking: Parts 1–3', 'Weekly mock test']::text[], 2, 4, 'teens', 4, 5, 90, 1100000, true, 3),
  ((select id from public.directions where slug = 'russian'), 'russian-kids', 'Bolalar uchun rus tili', 'Русский для детей', 'Russian for Kids', 'Maktabga tayyorgarlik va 1–4-sinf oʻquvchilari uchun rus tili: oʻqish, yozish va soʻzlashuv.', 'Русский язык для дошкольников и учеников 1–4 классов: чтение, письмо и разговор.', 'Russian for preschoolers and grades 1–4: reading, writing and speaking.', array['Alifbo va oʻqish', 'Yozuv va imlo', 'Soʻzlashuv mavzulari', 'Ertak va sheʼrlar']::text[], array['Алфавит и чтение', 'Письмо и орфография', 'Разговорные темы', 'Сказки и стихи']::text[], array['Alphabet and reading', 'Writing and spelling', 'Conversation topics', 'Fairy tales and poems']::text[], 1, 2, 'kids', 9, 3, 60, 550000, false, 4),
  ((select id from public.directions where slug = 'russian'), 'russian-general', 'Rus tili: soʻzlashuv va grammatika', 'Русский язык: разговор и грамматика', 'Russian: Speaking and Grammar', 'Oʻsmirlar va kattalar uchun: kelishiklar, feʼllar va erkin muloqot. Ish va oʻqish uchun rus tili.', 'Для подростков и взрослых: падежи, глаголы и свободное общение. Русский для учёбы и работы.', 'For teens and adults: cases, verbs and fluent conversation. Russian for study and work.', array['Kelishiklar tizimi', 'Feʼl turlari va zamonlar', 'Ish suhbati va hujjatlar', 'Erkin muloqot klubi']::text[], array['Система падежей', 'Виды глагола и времена', 'Деловое общение и документы', 'Разговорный клуб']::text[], array['The case system', 'Verb aspects and tenses', 'Business talk and documents', 'Conversation club']::text[], 1, 4, 'adults', 6, 3, 90, 650000, false, 5),
  ((select id from public.directions where slug = 'math'), 'math-school', 'Maktab matematikasi', 'Школьная математика', 'School Math', '5–9-sinflar uchun: mavzularni tushunib oʻrganish, baholarni oshirish va nazorat ishlariga tayyorgarlik.', 'Для 5–9 классов: понимание тем, рост оценок и подготовка к контрольным.', 'For grades 5–9: understanding topics, better grades and test preparation.', array['Kasrlar va foizlar', 'Tenglamalar', 'Geometriya asoslari', 'Nazorat ishiga tayyorgarlik']::text[], array['Дроби и проценты', 'Уравнения', 'Основы геометрии', 'Подготовка к контрольным']::text[], array['Fractions and percentages', 'Equations', 'Geometry basics', 'Test preparation']::text[], 1, 3, 'teens', 9, 3, 90, 600000, false, 6),
  ((select id from public.directions where slug = 'math'), 'math-olympiad', 'Olimpiada matematikasi', 'Олимпиадная математика', 'Olympiad Math', 'Kuchli oʻquvchilar uchun: nostandart masalalar, kombinatorika va sonlar nazariyasi. Tuman va shahar olimpiadalariga tayyorlov.', 'Для сильных учеников: нестандартные задачи, комбинаторика и теория чисел. Подготовка к районным и городским олимпиадам.', 'For strong students: non-standard problems, combinatorics and number theory. Preparation for district and city olympiads.', array['Sonlar nazariyasi', 'Kombinatorika', 'Olimpiada geometriyasi', 'Har oy sinov olimpiadasi']::text[], array['Теория чисел', 'Комбинаторика', 'Олимпиадная геометрия', 'Пробная олимпиада каждый месяц']::text[], array['Number theory', 'Combinatorics', 'Olympiad geometry', 'Monthly mock olympiad']::text[], 3, 4, 'teens', 9, 2, 120, 800000, true, 7),
  ((select id from public.directions where slug = 'abiturient'), 'abiturient-dtm', 'Abituriyent: DTM tayyorlov', 'Абитуриент: подготовка к DTM', 'University Entrance Prep', 'Oliy oʻquv yurtiga kirish testlariga tayyorlov: matematika va asosiy fan, haftalik DTM formatidagi sinov testlari.', 'Подготовка к вступительным тестам в вуз: математика и профильный предмет, еженедельные пробные тесты в формате DTM.', 'Preparation for university entrance tests: math and a core subject, weekly mock tests in DTM format.', array['Matematika: barcha mavzular', 'Asosiy fan boʻyicha chuqur tayyorlov', 'Haftalik DTM sinov testi', 'Vaqtni boshqarish strategiyasi']::text[], array['Математика: все темы', 'Углублённая подготовка по профильному предмету', 'Еженедельный пробный тест DTM', 'Стратегия управления временем']::text[], array['Math: all topics', 'In-depth core subject preparation', 'Weekly DTM mock test', 'Time management strategy']::text[], 1, 4, 'teens', 8, 5, 120, 900000, true, 8),
  ((select id from public.directions where slug = 'it'), 'python-kids', 'Bolalar uchun Python', 'Python для детей', 'Python for Kids', '9–13 yoshli bolalar uchun: oʻyinlar yaratish orqali dasturlash mantiqini oʻrganish.', 'Для детей 9–13 лет: изучаем логику программирования, создавая игры.', 'For kids aged 9–13: learning programming logic by building games.', array['Scratchʼdan Pythonʼga', 'Oʻzgaruvchilar va sikllar', 'Birinchi oʻyin', 'Yakuniy loyiha taqdimoti']::text[], array['От Scratch к Python', 'Переменные и циклы', 'Первая игра', 'Защита итогового проекта']::text[], array['From Scratch to Python', 'Variables and loops', 'Your first game', 'Final project demo']::text[], 1, 4, 'kids', 6, 2, 90, 700000, false, 9),
  ((select id from public.directions where slug = 'it'), 'frontend', 'Frontend dasturlash', 'Frontend-разработка', 'Frontend Development', 'HTML, CSS, JavaScript va React: noldan portfolio bilan ishga tayyor darajagacha.', 'HTML, CSS, JavaScript и React: с нуля до готового к работе уровня с портфолио.', 'HTML, CSS, JavaScript and React: from zero to job-ready with a portfolio.', array['HTML va CSS', 'JavaScript asoslari', 'React', 'Portfolio uchun 3 ta loyiha']::text[], array['HTML и CSS', 'Основы JavaScript', 'React', '3 проекта для портфолио']::text[], array['HTML and CSS', 'JavaScript basics', 'React', '3 portfolio projects']::text[], 1, 4, 'adults', 8, 3, 120, 1200000, true, 10),
  ((select id from public.directions where slug = 'it'), 'backend-python', 'Backend: Python va Django', 'Backend: Python и Django', 'Backend: Python and Django', 'Server dasturlash: Python, maʼlumotlar bazasi, API va deploy. Real loyiha jamoada.', 'Серверная разработка: Python, базы данных, API и деплой. Реальный проект в команде.', 'Server-side development: Python, databases, APIs and deployment. A real team project.', array['Python asoslari', 'SQL va PostgreSQL', 'Django va REST API', 'Jamoaviy loyiha']::text[], array['Основы Python', 'SQL и PostgreSQL', 'Django и REST API', 'Командный проект']::text[], array['Python basics', 'SQL and PostgreSQL', 'Django and REST APIs', 'Team project']::text[], 1, 4, 'adults', 8, 3, 120, 1200000, false, 11),
  ((select id from public.directions where slug = 'it'), 'ui-ux-design', 'UI/UX dizayn', 'UI/UX-дизайн', 'UI/UX Design', 'Figmaʼda ilova va saytlar dizayni: foydalanuvchi tadqiqoti, prototip va portfolio.', 'Дизайн приложений и сайтов в Figma: исследование пользователей, прототип и портфолио.', 'App and web design in Figma: user research, prototyping and a portfolio.', array['Dizayn asoslari va kompozitsiya', 'Figma', 'UX tadqiqot va prototip', 'Portfolio keys']::text[], array['Основы дизайна и композиция', 'Figma', 'UX-исследование и прототип', 'Кейс для портфолио']::text[], array['Design basics and composition', 'Figma', 'UX research and prototyping', 'Portfolio case study']::text[], 1, 4, 'adults', 5, 3, 120, 1000000, false, 12);

insert into public.teachers (full_name, photo_url, direction_id, experience_years, certificates, bio_uz, bio_ru, bio_en, sort) values
  ('Dilnoza Karimova', '/images/teachers/dilnoza.webp', (select id from public.directions where slug = 'english'), 7, array['IELTS 8.5', 'CELTA']::text[], 'IELTS boʻyicha 300 dan ortiq oʻquvchini 7.0+ natijaga olib chiqqan. Darslarida koʻproq gapirtiradi.', 'Подготовила более 300 учеников к IELTS 7.0+. На уроках больше всего говорят ученики.', 'Has taken 300+ students to IELTS 7.0+. In her lessons, students do most of the talking.', 1),
  ('Jasur Toshmatov', '/images/teachers/jasur.webp', (select id from public.directions where slug = 'english'), 5, array['IELTS 8.0', 'TKT']::text[], 'Bolalar va oʻsmirlar bilan ishlaydi. Oʻyin va loyihalar orqali oʻqitadi.', 'Работает с детьми и подростками. Учит через игры и проекты.', 'Works with kids and teens. Teaches through games and projects.', 2),
  ('Svetlana Kim', '/images/teachers/svetlana.webp', (select id from public.directions where slug = 'russian'), 12, array['Rus filologiyasi magistri']::text[], '12 yillik tajriba. Grammatikani jadval va misollar bilan oson tushuntiradi.', '12 лет опыта. Объясняет грамматику просто — через схемы и примеры.', '12 years of experience. Makes grammar simple with charts and examples.', 3),
  ('Bekzod Yusupov', '/images/teachers/bekzod.webp', (select id from public.directions where slug = 'math'), 9, array['Respublika olimpiadasi gʻolibi', 'Olimpiada murabbiyi']::text[], 'Oʻquvchilari shahar olimpiadalarida 40 dan ortiq sovrin olgan.', 'Его ученики взяли более 40 призов на городских олимпиадах.', 'His students have won 40+ prizes at city olympiads.', 4),
  ('Malika Ergasheva', '/images/teachers/malika.webp', (select id from public.directions where slug = 'abiturient'), 8, array['DTM 189 ball', 'Pedagogika magistri']::text[], 'Abituriyentlarni DTM formatida tayyorlaydi; har hafta sinov testi va tahlil.', 'Готовит абитуриентов в формате DTM: еженедельный пробный тест и разбор.', 'Prepares applicants in DTM format: a weekly mock test with review.', 5),
  ('Sardor Aliyev', '/images/teachers/sardor.webp', (select id from public.directions where slug = 'it'), 6, array['Senior Frontend Developer', 'React']::text[], 'Mahalliy IT kompaniyada senior frontend dasturchi. Darsda real loyihalar ustida ishlaydi.', 'Senior frontend-разработчик в местной IT-компании. На уроках — реальные проекты.', 'Senior frontend developer at a local IT company. Lessons are built around real projects.', 6),
  ('Nodira Saidova', '/images/teachers/nodira.webp', (select id from public.directions where slug = 'it'), 5, array['Product Designer', 'Google UX Certificate']::text[], 'Mahsulot dizayneri. 20 dan ortiq ilova va sayt dizaynini yaratgan.', 'Продуктовый дизайнер. Создала дизайн более 20 приложений и сайтов.', 'Product designer. Has designed 20+ apps and websites.', 7),
  ('Timur Abdullayev', '/images/teachers/timur.webp', (select id from public.directions where slug = 'it'), 7, array['Python Developer', 'Django']::text[], 'Backend dasturchi va bolalar uchun Python oʻqituvchisi. Murakkabni oddiy tilda tushuntiradi.', 'Backend-разработчик и преподаватель Python для детей. Объясняет сложное простым языком.', 'Backend developer and Python teacher for kids. Explains complex things in plain words.', 8);

insert into public.faq (question_uz, question_ru, question_en, answer_uz, answer_ru, answer_en, sort) values
  ('Sinov darsi haqiqatan bepulmi?', 'Пробный урок действительно бесплатный?', 'Is the trial lesson really free?', 'Ha, birinchi sinov darsi toʻliq bepul va hech qanday majburiyat yoʻq. Darsdan keyin oʻzingiz qaror qilasiz.', 'Да, первый пробный урок полностью бесплатный и ни к чему не обязывает. После урока вы решаете сами.', 'Yes, the first trial lesson is completely free with no obligation. You decide after the lesson.', 1),
  ('Narxlar qancha?', 'Сколько стоит обучение?', 'How much do courses cost?', 'Kurslar oyiga 550 000 soʻmdan 1 200 000 soʻmgacha. Aniq narx kurs sahifasida koʻrsatilgan.', 'Курсы стоят от 550 000 до 1 200 000 сумов в месяц. Точная цена указана на странице курса.', 'Courses cost from 550,000 to 1,200,000 UZS per month. The exact price is on each course page.', 2),
  ('Boʻlib toʻlash mumkinmi?', 'Можно ли платить частями?', 'Can I pay in instalments?', 'Ha, toʻlov har oy amalga oshiriladi. 3 oy uchun oldindan toʻlasangiz — 10% chegirma.', 'Да, оплата помесячная. При оплате за 3 месяца вперёд — скидка 10%.', 'Yes, payment is monthly. Pay for 3 months upfront and get 10% off.', 3),
  ('Chegirmalar bormi?', 'Есть ли скидки?', 'Are there any discounts?', 'Aka-uka va opa-singillar uchun ikkinchi farzandga 15% chegirma. Doʻstini olib kelgan oʻquvchiga 1 hafta bepul.', 'Для братьев и сестёр — скидка 15% на второго ребёнка. Привёл друга — неделя обучения бесплатно.', 'Siblings get 15% off for the second child. Bring a friend and get one week free.', 4),
  ('Guruhda nechta oʻquvchi boʻladi?', 'Сколько учеников в группе?', 'How many students are in a group?', 'Guruhlarda 8 tadan 12 tagacha oʻquvchi. Bolalar guruhlarida — 10 tagacha.', 'В группах от 8 до 12 учеников. В детских группах — до 10.', 'Groups have 8 to 12 students. Kids'' groups have up to 10.', 5),
  ('Agar natija boʻlmasa-chi?', 'А если не будет результата?', 'What if I don''t see results?', 'Birinchi oy oxirida oʻquvchi darajasi tekshiriladi. Natija boʻlmasa, keyingi oy bepul.', 'В конце первого месяца проверяем уровень. Если результата нет — следующий месяц бесплатно.', 'We check the student''s level at the end of the first month. No progress means the next month is free.', 6),
  ('Darslar qaysi tilda oʻtadi?', 'На каком языке проходят занятия?', 'What language are classes taught in?', 'Tushuntirishlar oʻzbek yoki rus tilida — guruh tanlovingizga qarab. Til kurslarida asosiy amaliyot oʻqitilayotgan tilda.', 'Объяснения на узбекском или русском — по выбору группы. На языковых курсах основная практика — на изучаемом языке.', 'Explanations are in Uzbek or Russian depending on the group. Language courses practise mostly in the target language.', 7),
  ('Darsni oʻtkazib yuborsam nima boʻladi?', 'Что если я пропущу урок?', 'What if I miss a class?', 'Har bir dars yozib olinadi va Telegram guruhga yuboriladi. Oʻqituvchi bilan qoʻshimcha konsultatsiya ham bor.', 'Каждый урок записывается и отправляется в Telegram-группу. Есть дополнительные консультации с преподавателем.', 'Every lesson is recorded and shared in the Telegram group. Extra consultations with the teacher are available.', 8),
  ('Qaysi filial menga yaqin?', 'Какой филиал ближе ко мне?', 'Which branch is closest to me?', 'Bizda 3 ta filial bor: Chilonzor (Novza metro), Yunusobod (Yunusobod metro) va Mirzo Ulugʻbek (Buyuk Ipak Yoʻli metro).', 'У нас 3 филиала: Чиланзар (метро Новза), Юнусабад (метро Юнусабад) и Мирзо-Улугбек (метро Буюк Ипак Йули).', 'We have 3 branches: Chilanzar (Novza metro), Yunusabad (Yunusabad metro) and Mirzo Ulugbek (Buyuk Ipak Yuli metro).', 9),
  ('Necha yoshdan qabul qilasiz?', 'С какого возраста принимаете?', 'From what age do you accept students?', '7 yoshdan boshlab. 7–11 yoshli bolalar uchun alohida oʻyin uslubidagi kurslar bor.', 'С 7 лет. Для детей 7–11 лет есть отдельные курсы в игровом формате.', 'From age 7. Children aged 7–11 have separate game-based courses.', 10);

insert into public.testimonials (name, direction_id, achievement_uz, achievement_ru, achievement_en, text_uz, text_ru, text_en, photo_url, is_demo, sort) values
  ('Aziz, 17', (select id from public.directions where slug = 'english'), 'IELTS 7.5', 'IELTS 7.5', 'IELTS 7.5', '4 oyda 5.5 dan 7.5 ga chiqdim. Har hafta mock test eng koʻp yordam berdi.', 'За 4 месяца поднялся с 5.5 до 7.5. Больше всего помогли еженедельные mock-тесты.', 'I went from 5.5 to 7.5 in 4 months. The weekly mock tests helped the most.', '/images/testimonials/1.webp', true, 1),
  ('Madina, 15', (select id from public.directions where slug = 'math'), 'Shahar olimpiadasi, 2-oʻrin', 'Городская олимпиада, 2 место', 'City olympiad, 2nd place', 'Oldin olimpiada masalalaridan qoʻrqardim, endi ularni yechish eng qiziq mashgʻulotim.', 'Раньше боялась олимпиадных задач, теперь это моё любимое занятие.', 'I used to be afraid of olympiad problems — now solving them is my favourite thing.', '/images/testimonials/2.webp', true, 2),
  ('Sevara opa (ota-ona)', (select id from public.directions where slug = 'russian'), 'Oʻgʻli 3 oyda erkin gapira boshladi', 'Сын за 3 месяца заговорил свободно', 'Her son speaks freely after 3 months', 'Oʻgʻlim maktabda rus tilidan qiynalardi. 3 oyda baholari 5 ga chiqdi, endi oʻzi kitob oʻqiydi.', 'Сыну было тяжело с русским в школе. За 3 месяца оценки выросли до пятёрок, теперь он сам читает книги.', 'My son struggled with Russian at school. In 3 months his grades went up to top marks and now he reads books himself.', '/images/testimonials/3.webp', true, 3),
  ('Javohir, 22', (select id from public.directions where slug = 'it'), 'Junior Frontend dasturchi', 'Junior Frontend-разработчик', 'Junior Frontend Developer', 'Kurs tugashidan oldin portfoliodagi loyiham bilan ishga qabul qilindim.', 'Меня взяли на работу ещё до окончания курса — благодаря проекту из портфолио.', 'I got hired before the course ended thanks to my portfolio project.', '/images/testimonials/4.webp', true, 4),
  ('Shahzoda, 18', (select id from public.directions where slug = 'abiturient'), 'DTM: 184 ball, grant', 'DTM: 184 балла, грант', 'DTM: 184 points, scholarship', 'Haftalik sinov testlari imtihonda hayajonni yoʻqotdi. Grant asosida oʻqishga kirdim.', 'Еженедельные пробные тесты сняли волнение на экзамене. Поступила на грант.', 'Weekly mock tests took away my exam nerves. I got into university on a scholarship.', '/images/testimonials/5.webp', true, 5),
  ('Bobur, 10', (select id from public.directions where slug = 'it'), 'Birinchi oʻyinini yaratdi', 'Создал свою первую игру', 'Built his first game', 'Pythonʼda oʻzim oʻyin yasadim va uni doʻstlarimga koʻrsatdim!', 'Я сам сделал игру на Python и показал её друзьям!', 'I made my own game in Python and showed it to my friends!', '/images/testimonials/6.webp', true, 6);

insert into public.test_questions (direction_id, level, question, options, correct_key, sort) values
  ((select id from public.directions where slug = 'english'), 1, '{"uz": "She ___ a student.", "ru": "She ___ a student.", "en": "She ___ a student."}'::jsonb, '[{"key": "a", "text": {"uz": "am", "ru": "am", "en": "am"}}, {"key": "b", "text": {"uz": "is", "ru": "is", "en": "is"}}, {"key": "c", "text": {"uz": "are", "ru": "are", "en": "are"}}, {"key": "d", "text": {"uz": "be", "ru": "be", "en": "be"}}]'::jsonb, 'b', 10),
  ((select id from public.directions where slug = 'english'), 1, '{"uz": "I ___ to school every day.", "ru": "I ___ to school every day.", "en": "I ___ to school every day."}'::jsonb, '[{"key": "a", "text": {"uz": "goes", "ru": "goes", "en": "goes"}}, {"key": "b", "text": {"uz": "going", "ru": "going", "en": "going"}}, {"key": "c", "text": {"uz": "go", "ru": "go", "en": "go"}}, {"key": "d", "text": {"uz": "gone", "ru": "gone", "en": "gone"}}]'::jsonb, 'c', 11),
  ((select id from public.directions where slug = 'english'), 1, '{"uz": "There ___ two apples on the table.", "ru": "There ___ two apples on the table.", "en": "There ___ two apples on the table."}'::jsonb, '[{"key": "a", "text": {"uz": "is", "ru": "is", "en": "is"}}, {"key": "b", "text": {"uz": "are", "ru": "are", "en": "are"}}, {"key": "c", "text": {"uz": "am", "ru": "am", "en": "am"}}, {"key": "d", "text": {"uz": "be", "ru": "be", "en": "be"}}]'::jsonb, 'b', 12),
  ((select id from public.directions where slug = 'english'), 1, '{"uz": "What is the opposite of “hot”?", "ru": "What is the opposite of “hot”?", "en": "What is the opposite of “hot”?"}'::jsonb, '[{"key": "a", "text": {"uz": "cold", "ru": "cold", "en": "cold"}}, {"key": "b", "text": {"uz": "warm", "ru": "warm", "en": "warm"}}, {"key": "c", "text": {"uz": "big", "ru": "big", "en": "big"}}, {"key": "d", "text": {"uz": "fast", "ru": "fast", "en": "fast"}}]'::jsonb, 'a', 13),
  ((select id from public.directions where slug = 'english'), 1, '{"uz": "___ you like coffee?", "ru": "___ you like coffee?", "en": "___ you like coffee?"}'::jsonb, '[{"key": "a", "text": {"uz": "Does", "ru": "Does", "en": "Does"}}, {"key": "b", "text": {"uz": "Is", "ru": "Is", "en": "Is"}}, {"key": "c", "text": {"uz": "Do", "ru": "Do", "en": "Do"}}, {"key": "d", "text": {"uz": "Are", "ru": "Are", "en": "Are"}}]'::jsonb, 'c', 14),
  ((select id from public.directions where slug = 'english'), 2, '{"uz": "If it rains tomorrow, we ___ at home.", "ru": "If it rains tomorrow, we ___ at home.", "en": "If it rains tomorrow, we ___ at home."}'::jsonb, '[{"key": "a", "text": {"uz": "stay", "ru": "stay", "en": "stay"}}, {"key": "b", "text": {"uz": "will stay", "ru": "will stay", "en": "will stay"}}, {"key": "c", "text": {"uz": "stayed", "ru": "stayed", "en": "stayed"}}, {"key": "d", "text": {"uz": "would stayed", "ru": "would stayed", "en": "would stayed"}}]'::jsonb, 'b', 20),
  ((select id from public.directions where slug = 'english'), 2, '{"uz": "I have lived here ___ 2019.", "ru": "I have lived here ___ 2019.", "en": "I have lived here ___ 2019."}'::jsonb, '[{"key": "a", "text": {"uz": "for", "ru": "for", "en": "for"}}, {"key": "b", "text": {"uz": "since", "ru": "since", "en": "since"}}, {"key": "c", "text": {"uz": "from", "ru": "from", "en": "from"}}, {"key": "d", "text": {"uz": "at", "ru": "at", "en": "at"}}]'::jsonb, 'b', 21),
  ((select id from public.directions where slug = 'english'), 2, '{"uz": "She asked me where ___.", "ru": "She asked me where ___.", "en": "She asked me where ___."}'::jsonb, '[{"key": "a", "text": {"uz": "did I live", "ru": "did I live", "en": "did I live"}}, {"key": "b", "text": {"uz": "I lived", "ru": "I lived", "en": "I lived"}}, {"key": "c", "text": {"uz": "do I live", "ru": "do I live", "en": "do I live"}}, {"key": "d", "text": {"uz": "I do live", "ru": "I do live", "en": "I do live"}}]'::jsonb, 'b', 22),
  ((select id from public.directions where slug = 'english'), 2, '{"uz": "This is the ___ film I have ever seen.", "ru": "This is the ___ film I have ever seen.", "en": "This is the ___ film I have ever seen."}'::jsonb, '[{"key": "a", "text": {"uz": "more interesting", "ru": "more interesting", "en": "more interesting"}}, {"key": "b", "text": {"uz": "most interesting", "ru": "most interesting", "en": "most interesting"}}, {"key": "c", "text": {"uz": "interestinger", "ru": "interestinger", "en": "interestinger"}}, {"key": "d", "text": {"uz": "much interesting", "ru": "much interesting", "en": "much interesting"}}]'::jsonb, 'b', 23),
  ((select id from public.directions where slug = 'english'), 2, '{"uz": "I''m looking forward ___ you.", "ru": "I''m looking forward ___ you.", "en": "I''m looking forward ___ you."}'::jsonb, '[{"key": "a", "text": {"uz": "to see", "ru": "to see", "en": "to see"}}, {"key": "b", "text": {"uz": "see", "ru": "see", "en": "see"}}, {"key": "c", "text": {"uz": "to seeing", "ru": "to seeing", "en": "to seeing"}}, {"key": "d", "text": {"uz": "seeing", "ru": "seeing", "en": "seeing"}}]'::jsonb, 'c', 24),
  ((select id from public.directions where slug = 'english'), 3, '{"uz": "By the time we arrived, the film ___.", "ru": "By the time we arrived, the film ___.", "en": "By the time we arrived, the film ___."}'::jsonb, '[{"key": "a", "text": {"uz": "already started", "ru": "already started", "en": "already started"}}, {"key": "b", "text": {"uz": "has already started", "ru": "has already started", "en": "has already started"}}, {"key": "c", "text": {"uz": "had already started", "ru": "had already started", "en": "had already started"}}, {"key": "d", "text": {"uz": "was already start", "ru": "was already start", "en": "was already start"}}]'::jsonb, 'c', 30),
  ((select id from public.directions where slug = 'english'), 3, '{"uz": "I wish I ___ more time to study.", "ru": "I wish I ___ more time to study.", "en": "I wish I ___ more time to study."}'::jsonb, '[{"key": "a", "text": {"uz": "have", "ru": "have", "en": "have"}}, {"key": "b", "text": {"uz": "had", "ru": "had", "en": "had"}}, {"key": "c", "text": {"uz": "will have", "ru": "will have", "en": "will have"}}, {"key": "d", "text": {"uz": "am having", "ru": "am having", "en": "am having"}}]'::jsonb, 'b', 31),
  ((select id from public.directions where slug = 'english'), 3, '{"uz": "The report ___ by the manager yesterday.", "ru": "The report ___ by the manager yesterday.", "en": "The report ___ by the manager yesterday."}'::jsonb, '[{"key": "a", "text": {"uz": "was approved", "ru": "was approved", "en": "was approved"}}, {"key": "b", "text": {"uz": "approved", "ru": "approved", "en": "approved"}}, {"key": "c", "text": {"uz": "has approved", "ru": "has approved", "en": "has approved"}}, {"key": "d", "text": {"uz": "was approving", "ru": "was approving", "en": "was approving"}}]'::jsonb, 'a', 32),
  ((select id from public.directions where slug = 'english'), 3, '{"uz": "He denied ___ the window.", "ru": "He denied ___ the window.", "en": "He denied ___ the window."}'::jsonb, '[{"key": "a", "text": {"uz": "to break", "ru": "to break", "en": "to break"}}, {"key": "b", "text": {"uz": "breaking", "ru": "breaking", "en": "breaking"}}, {"key": "c", "text": {"uz": "break", "ru": "break", "en": "break"}}, {"key": "d", "text": {"uz": "broke", "ru": "broke", "en": "broke"}}]'::jsonb, 'b', 33),
  ((select id from public.directions where slug = 'english'), 3, '{"uz": "Choose the closest meaning to “reluctant”.", "ru": "Choose the closest meaning to “reluctant”.", "en": "Choose the closest meaning to “reluctant”."}'::jsonb, '[{"key": "a", "text": {"uz": "eager", "ru": "eager", "en": "eager"}}, {"key": "b", "text": {"uz": "unwilling", "ru": "unwilling", "en": "unwilling"}}, {"key": "c", "text": {"uz": "careful", "ru": "careful", "en": "careful"}}, {"key": "d", "text": {"uz": "tired", "ru": "tired", "en": "tired"}}]'::jsonb, 'b', 34),
  ((select id from public.directions where slug = 'english'), 4, '{"uz": "Hardly ___ the meeting started when the fire alarm went off.", "ru": "Hardly ___ the meeting started when the fire alarm went off.", "en": "Hardly ___ the meeting started when the fire alarm went off."}'::jsonb, '[{"key": "a", "text": {"uz": "had", "ru": "had", "en": "had"}}, {"key": "b", "text": {"uz": "has", "ru": "has", "en": "has"}}, {"key": "c", "text": {"uz": "did", "ru": "did", "en": "did"}}, {"key": "d", "text": {"uz": "was", "ru": "was", "en": "was"}}]'::jsonb, 'a', 40),
  ((select id from public.directions where slug = 'english'), 4, '{"uz": "Not until later ___ how serious the problem was.", "ru": "Not until later ___ how serious the problem was.", "en": "Not until later ___ how serious the problem was."}'::jsonb, '[{"key": "a", "text": {"uz": "we realised", "ru": "we realised", "en": "we realised"}}, {"key": "b", "text": {"uz": "did we realise", "ru": "did we realise", "en": "did we realise"}}, {"key": "c", "text": {"uz": "we did realise", "ru": "we did realise", "en": "we did realise"}}, {"key": "d", "text": {"uz": "realised we", "ru": "realised we", "en": "realised we"}}]'::jsonb, 'b', 41),
  ((select id from public.directions where slug = 'english'), 4, '{"uz": "Had I known about the traffic, I ___ earlier.", "ru": "Had I known about the traffic, I ___ earlier.", "en": "Had I known about the traffic, I ___ earlier."}'::jsonb, '[{"key": "a", "text": {"uz": "would leave", "ru": "would leave", "en": "would leave"}}, {"key": "b", "text": {"uz": "would have left", "ru": "would have left", "en": "would have left"}}, {"key": "c", "text": {"uz": "will leave", "ru": "will leave", "en": "will leave"}}, {"key": "d", "text": {"uz": "left", "ru": "left", "en": "left"}}]'::jsonb, 'b', 42),
  ((select id from public.directions where slug = 'english'), 4, '{"uz": "The proposal was rejected on the ___ that it was too expensive.", "ru": "The proposal was rejected on the ___ that it was too expensive.", "en": "The proposal was rejected on the ___ that it was too expensive."}'::jsonb, '[{"key": "a", "text": {"uz": "grounds", "ru": "grounds", "en": "grounds"}}, {"key": "b", "text": {"uz": "reasons", "ru": "reasons", "en": "reasons"}}, {"key": "c", "text": {"uz": "basis", "ru": "basis", "en": "basis"}}, {"key": "d", "text": {"uz": "causes", "ru": "causes", "en": "causes"}}]'::jsonb, 'a', 43),
  ((select id from public.directions where slug = 'english'), 4, '{"uz": "Choose the word closest to “meticulous”.", "ru": "Choose the word closest to “meticulous”.", "en": "Choose the word closest to “meticulous”."}'::jsonb, '[{"key": "a", "text": {"uz": "careless", "ru": "careless", "en": "careless"}}, {"key": "b", "text": {"uz": "thorough", "ru": "thorough", "en": "thorough"}}, {"key": "c", "text": {"uz": "quick", "ru": "quick", "en": "quick"}}, {"key": "d", "text": {"uz": "generous", "ru": "generous", "en": "generous"}}]'::jsonb, 'b', 44),
  ((select id from public.directions where slug = 'russian'), 1, '{"uz": "Как ___ зовут?", "ru": "Как ___ зовут?", "en": "Как ___ зовут?"}'::jsonb, '[{"key": "a", "text": {"uz": "тебя", "ru": "тебя", "en": "тебя"}}, {"key": "b", "text": {"uz": "ты", "ru": "ты", "en": "ты"}}, {"key": "c", "text": {"uz": "тебе", "ru": "тебе", "en": "тебе"}}, {"key": "d", "text": {"uz": "твой", "ru": "твой", "en": "твой"}}]'::jsonb, 'a', 10),
  ((select id from public.directions where slug = 'russian'), 1, '{"uz": "Я ___ в Ташкенте.", "ru": "Я ___ в Ташкенте.", "en": "Я ___ в Ташкенте."}'::jsonb, '[{"key": "a", "text": {"uz": "живёт", "ru": "живёт", "en": "живёт"}}, {"key": "b", "text": {"uz": "живу", "ru": "живу", "en": "живу"}}, {"key": "c", "text": {"uz": "живут", "ru": "живут", "en": "живут"}}, {"key": "d", "text": {"uz": "жить", "ru": "жить", "en": "жить"}}]'::jsonb, 'b', 11),
  ((select id from public.directions where slug = 'russian'), 1, '{"uz": "Это ___ книга.", "ru": "Это ___ книга.", "en": "Это ___ книга."}'::jsonb, '[{"key": "a", "text": {"uz": "мой", "ru": "мой", "en": "мой"}}, {"key": "b", "text": {"uz": "моё", "ru": "моё", "en": "моё"}}, {"key": "c", "text": {"uz": "моя", "ru": "моя", "en": "моя"}}, {"key": "d", "text": {"uz": "мои", "ru": "мои", "en": "мои"}}]'::jsonb, 'c', 12),
  ((select id from public.directions where slug = 'russian'), 1, '{"uz": "У меня есть ___.", "ru": "У меня есть ___.", "en": "У меня есть ___."}'::jsonb, '[{"key": "a", "text": {"uz": "сестра", "ru": "сестра", "en": "сестра"}}, {"key": "b", "text": {"uz": "сестру", "ru": "сестру", "en": "сестру"}}, {"key": "c", "text": {"uz": "сестре", "ru": "сестре", "en": "сестре"}}, {"key": "d", "text": {"uz": "сестрой", "ru": "сестрой", "en": "сестрой"}}]'::jsonb, 'a', 13),
  ((select id from public.directions where slug = 'russian'), 1, '{"uz": "Мы ___ в школу утром.", "ru": "Мы ___ в школу утром.", "en": "Мы ___ в школу утром."}'::jsonb, '[{"key": "a", "text": {"uz": "иду", "ru": "иду", "en": "иду"}}, {"key": "b", "text": {"uz": "идёшь", "ru": "идёшь", "en": "идёшь"}}, {"key": "c", "text": {"uz": "идём", "ru": "идём", "en": "идём"}}, {"key": "d", "text": {"uz": "идут", "ru": "идут", "en": "идут"}}]'::jsonb, 'c', 14),
  ((select id from public.directions where slug = 'russian'), 2, '{"uz": "Я давно не видел ___ брата.", "ru": "Я давно не видел ___ брата.", "en": "Я давно не видел ___ брата."}'::jsonb, '[{"key": "a", "text": {"uz": "мой", "ru": "мой", "en": "мой"}}, {"key": "b", "text": {"uz": "моего", "ru": "моего", "en": "моего"}}, {"key": "c", "text": {"uz": "моему", "ru": "моему", "en": "моему"}}, {"key": "d", "text": {"uz": "моим", "ru": "моим", "en": "моим"}}]'::jsonb, 'b', 20),
  ((select id from public.directions where slug = 'russian'), 2, '{"uz": "Завтра я ___ домашнее задание.", "ru": "Завтра я ___ домашнее задание.", "en": "Завтра я ___ домашнее задание."}'::jsonb, '[{"key": "a", "text": {"uz": "делал", "ru": "делал", "en": "делал"}}, {"key": "b", "text": {"uz": "сделаю", "ru": "сделаю", "en": "сделаю"}}, {"key": "c", "text": {"uz": "сделал", "ru": "сделал", "en": "сделал"}}, {"key": "d", "text": {"uz": "делала", "ru": "делала", "en": "делала"}}]'::jsonb, 'b', 21),
  ((select id from public.directions where slug = 'russian'), 2, '{"uz": "Она интересуется ___.", "ru": "Она интересуется ___.", "en": "Она интересуется ___."}'::jsonb, '[{"key": "a", "text": {"uz": "музыка", "ru": "музыка", "en": "музыка"}}, {"key": "b", "text": {"uz": "музыку", "ru": "музыку", "en": "музыку"}}, {"key": "c", "text": {"uz": "музыкой", "ru": "музыкой", "en": "музыкой"}}, {"key": "d", "text": {"uz": "музыке", "ru": "музыке", "en": "музыке"}}]'::jsonb, 'c', 22),
  ((select id from public.directions where slug = 'russian'), 2, '{"uz": "Мы говорили ___ новом фильме.", "ru": "Мы говорили ___ новом фильме.", "en": "Мы говорили ___ новом фильме."}'::jsonb, '[{"key": "a", "text": {"uz": "о", "ru": "о", "en": "о"}}, {"key": "b", "text": {"uz": "об", "ru": "об", "en": "об"}}, {"key": "c", "text": {"uz": "в", "ru": "в", "en": "в"}}, {"key": "d", "text": {"uz": "на", "ru": "на", "en": "на"}}]'::jsonb, 'a', 23),
  ((select id from public.directions where slug = 'russian'), 2, '{"uz": "Если будет хорошая погода, мы ___ в парк.", "ru": "Если будет хорошая погода, мы ___ в парк.", "en": "Если будет хорошая погода, мы ___ в парк."}'::jsonb, '[{"key": "a", "text": {"uz": "пошли бы", "ru": "пошли бы", "en": "пошли бы"}}, {"key": "b", "text": {"uz": "пойдём", "ru": "пойдём", "en": "пойдём"}}, {"key": "c", "text": {"uz": "шли", "ru": "шли", "en": "шли"}}, {"key": "d", "text": {"uz": "пойти", "ru": "пойти", "en": "пойти"}}]'::jsonb, 'b', 24),
  ((select id from public.directions where slug = 'russian'), 3, '{"uz": "Книга, ___ я прочитал, очень интересная.", "ru": "Книга, ___ я прочитал, очень интересная.", "en": "Книга, ___ я прочитал, очень интересная."}'::jsonb, '[{"key": "a", "text": {"uz": "который", "ru": "который", "en": "который"}}, {"key": "b", "text": {"uz": "которая", "ru": "которая", "en": "которая"}}, {"key": "c", "text": {"uz": "которую", "ru": "которую", "en": "которую"}}, {"key": "d", "text": {"uz": "которой", "ru": "которой", "en": "которой"}}]'::jsonb, 'c', 30),
  ((select id from public.directions where slug = 'russian'), 3, '{"uz": "Он пришёл, ___ урок уже закончился.", "ru": "Он пришёл, ___ урок уже закончился.", "en": "Он пришёл, ___ урок уже закончился."}'::jsonb, '[{"key": "a", "text": {"uz": "чтобы", "ru": "чтобы", "en": "чтобы"}}, {"key": "b", "text": {"uz": "когда", "ru": "когда", "en": "когда"}}, {"key": "c", "text": {"uz": "если", "ru": "если", "en": "если"}}, {"key": "d", "text": {"uz": "хотя", "ru": "хотя", "en": "хотя"}}]'::jsonb, 'b', 31),
  ((select id from public.directions where slug = 'russian'), 3, '{"uz": "Нам нужно ___ к экзамену.", "ru": "Нам нужно ___ к экзамену.", "en": "Нам нужно ___ к экзамену."}'::jsonb, '[{"key": "a", "text": {"uz": "подготовиться", "ru": "подготовиться", "en": "подготовиться"}}, {"key": "b", "text": {"uz": "подготовится", "ru": "подготовится", "en": "подготовится"}}, {"key": "c", "text": {"uz": "подготовимся", "ru": "подготовимся", "en": "подготовимся"}}, {"key": "d", "text": {"uz": "подготовка", "ru": "подготовка", "en": "подготовка"}}]'::jsonb, 'a', 32),
  ((select id from public.directions where slug = 'russian'), 3, '{"uz": "Подберите синоним к слову «быстро».", "ru": "Подберите синоним к слову «быстро».", "en": "Подберите синоним к слову «быстро»."}'::jsonb, '[{"key": "a", "text": {"uz": "медленно", "ru": "медленно", "en": "медленно"}}, {"key": "b", "text": {"uz": "стремительно", "ru": "стремительно", "en": "стремительно"}}, {"key": "c", "text": {"uz": "спокойно", "ru": "спокойно", "en": "спокойно"}}, {"key": "d", "text": {"uz": "тихо", "ru": "тихо", "en": "тихо"}}]'::jsonb, 'b', 33),
  ((select id from public.directions where slug = 'russian'), 3, '{"uz": "Я хочу, чтобы ты ___ мне завтра.", "ru": "Я хочу, чтобы ты ___ мне завтра.", "en": "Я хочу, чтобы ты ___ мне завтра."}'::jsonb, '[{"key": "a", "text": {"uz": "позвонишь", "ru": "позвонишь", "en": "позвонишь"}}, {"key": "b", "text": {"uz": "позвонил", "ru": "позвонил", "en": "позвонил"}}, {"key": "c", "text": {"uz": "звонишь", "ru": "звонишь", "en": "звонишь"}}, {"key": "d", "text": {"uz": "позвонить", "ru": "позвонить", "en": "позвонить"}}]'::jsonb, 'b', 34),
  ((select id from public.directions where slug = 'russian'), 4, '{"uz": "Несмотря ___ дождь, мы пошли гулять.", "ru": "Несмотря ___ дождь, мы пошли гулять.", "en": "Несмотря ___ дождь, мы пошли гулять."}'::jsonb, '[{"key": "a", "text": {"uz": "на", "ru": "на", "en": "на"}}, {"key": "b", "text": {"uz": "в", "ru": "в", "en": "в"}}, {"key": "c", "text": {"uz": "о", "ru": "о", "en": "о"}}, {"key": "d", "text": {"uz": "за", "ru": "за", "en": "за"}}]'::jsonb, 'a', 40),
  ((select id from public.directions where slug = 'russian'), 4, '{"uz": "Выберите правильно написанное слово.", "ru": "Выберите правильно написанное слово.", "en": "Выберите правильно написанное слово."}'::jsonb, '[{"key": "a", "text": {"uz": "расчёт", "ru": "расчёт", "en": "расчёт"}}, {"key": "b", "text": {"uz": "рассчёт", "ru": "рассчёт", "en": "рассчёт"}}, {"key": "c", "text": {"uz": "росчёт", "ru": "росчёт", "en": "росчёт"}}, {"key": "d", "text": {"uz": "расщёт", "ru": "расщёт", "en": "расщёт"}}]'::jsonb, 'a', 41),
  ((select id from public.directions where slug = 'russian'), 4, '{"uz": "Ему было не ___ смеха.", "ru": "Ему было не ___ смеха.", "en": "Ему было не ___ смеха."}'::jsonb, '[{"key": "a", "text": {"uz": "к", "ru": "к", "en": "к"}}, {"key": "b", "text": {"uz": "до", "ru": "до", "en": "до"}}, {"key": "c", "text": {"uz": "для", "ru": "для", "en": "для"}}, {"key": "d", "text": {"uz": "от", "ru": "от", "en": "от"}}]'::jsonb, 'b', 42),
  ((select id from public.directions where slug = 'russian'), 4, '{"uz": "Выражение «бить баклуши» означает:", "ru": "Выражение «бить баклуши» означает:", "en": "Выражение «бить баклуши» означает:"}'::jsonb, '[{"key": "a", "text": {"uz": "много работать", "ru": "много работать", "en": "много работать"}}, {"key": "b", "text": {"uz": "бездельничать", "ru": "бездельничать", "en": "бездельничать"}}, {"key": "c", "text": {"uz": "драться", "ru": "драться", "en": "драться"}}, {"key": "d", "text": {"uz": "готовить еду", "ru": "готовить еду", "en": "готовить еду"}}]'::jsonb, 'b', 43),
  ((select id from public.directions where slug = 'russian'), 4, '{"uz": "Какое слово пишется с НЕ слитно?", "ru": "Какое слово пишется с НЕ слитно?", "en": "Какое слово пишется с НЕ слитно?"}'::jsonb, '[{"key": "a", "text": {"uz": "(не)был", "ru": "(не)был", "en": "(не)был"}}, {"key": "b", "text": {"uz": "(не)навидеть", "ru": "(не)навидеть", "en": "(не)навидеть"}}, {"key": "c", "text": {"uz": "(не)могу", "ru": "(не)могу", "en": "(не)могу"}}, {"key": "d", "text": {"uz": "(не)знал", "ru": "(не)знал", "en": "(не)знал"}}]'::jsonb, 'b', 44),
  ((select id from public.directions where slug = 'math'), 1, '{"uz": "15 + 27 = ?", "ru": "15 + 27 = ?", "en": "15 + 27 = ?"}'::jsonb, '[{"key": "a", "text": {"uz": "32", "ru": "32", "en": "32"}}, {"key": "b", "text": {"uz": "42", "ru": "42", "en": "42"}}, {"key": "c", "text": {"uz": "43", "ru": "43", "en": "43"}}, {"key": "d", "text": {"uz": "52", "ru": "52", "en": "52"}}]'::jsonb, 'b', 10),
  ((select id from public.directions where slug = 'math'), 1, '{"uz": "8 × 7 = ?", "ru": "8 × 7 = ?", "en": "8 × 7 = ?"}'::jsonb, '[{"key": "a", "text": {"uz": "54", "ru": "54", "en": "54"}}, {"key": "b", "text": {"uz": "56", "ru": "56", "en": "56"}}, {"key": "c", "text": {"uz": "63", "ru": "63", "en": "63"}}, {"key": "d", "text": {"uz": "48", "ru": "48", "en": "48"}}]'::jsonb, 'b', 11),
  ((select id from public.directions where slug = 'math'), 1, '{"uz": "100 − 37 = ?", "ru": "100 − 37 = ?", "en": "100 − 37 = ?"}'::jsonb, '[{"key": "a", "text": {"uz": "63", "ru": "63", "en": "63"}}, {"key": "b", "text": {"uz": "73", "ru": "73", "en": "73"}}, {"key": "c", "text": {"uz": "67", "ru": "67", "en": "67"}}, {"key": "d", "text": {"uz": "53", "ru": "53", "en": "53"}}]'::jsonb, 'a', 12),
  ((select id from public.directions where slug = 'math'), 1, '{"uz": "1/2 + 1/4 = ?", "ru": "1/2 + 1/4 = ?", "en": "1/2 + 1/4 = ?"}'::jsonb, '[{"key": "a", "text": {"uz": "2/6", "ru": "2/6", "en": "2/6"}}, {"key": "b", "text": {"uz": "3/4", "ru": "3/4", "en": "3/4"}}, {"key": "c", "text": {"uz": "1/3", "ru": "1/3", "en": "1/3"}}, {"key": "d", "text": {"uz": "2/4", "ru": "2/4", "en": "2/4"}}]'::jsonb, 'b', 13),
  ((select id from public.directions where slug = 'math'), 1, '{"uz": "36 ni 4 ga boʻling.", "ru": "Разделите 36 на 4.", "en": "Divide 36 by 4."}'::jsonb, '[{"key": "a", "text": {"uz": "8", "ru": "8", "en": "8"}}, {"key": "b", "text": {"uz": "9", "ru": "9", "en": "9"}}, {"key": "c", "text": {"uz": "6", "ru": "6", "en": "6"}}, {"key": "d", "text": {"uz": "12", "ru": "12", "en": "12"}}]'::jsonb, 'b', 14),
  ((select id from public.directions where slug = 'math'), 2, '{"uz": "Tenglamani yeching: 3x + 5 = 20", "ru": "Решите уравнение: 3x + 5 = 20", "en": "Solve: 3x + 5 = 20"}'::jsonb, '[{"key": "a", "text": {"uz": "3", "ru": "3", "en": "3"}}, {"key": "b", "text": {"uz": "5", "ru": "5", "en": "5"}}, {"key": "c", "text": {"uz": "7", "ru": "7", "en": "7"}}, {"key": "d", "text": {"uz": "25/3", "ru": "25/3", "en": "25/3"}}]'::jsonb, 'b', 20),
  ((select id from public.directions where slug = 'math'), 2, '{"uz": "150 ning 20% i nechaga teng?", "ru": "Чему равны 20% от 150?", "en": "What is 20% of 150?"}'::jsonb, '[{"key": "a", "text": {"uz": "20", "ru": "20", "en": "20"}}, {"key": "b", "text": {"uz": "30", "ru": "30", "en": "30"}}, {"key": "c", "text": {"uz": "15", "ru": "15", "en": "15"}}, {"key": "d", "text": {"uz": "35", "ru": "35", "en": "35"}}]'::jsonb, 'b', 21),
  ((select id from public.directions where slug = 'math'), 2, '{"uz": "Tomonlari 6 va 4 boʻlgan toʻgʻri toʻrtburchak yuzi:", "ru": "Площадь прямоугольника со сторонами 6 и 4:", "en": "Area of a rectangle with sides 6 and 4:"}'::jsonb, '[{"key": "a", "text": {"uz": "20", "ru": "20", "en": "20"}}, {"key": "b", "text": {"uz": "24", "ru": "24", "en": "24"}}, {"key": "c", "text": {"uz": "10", "ru": "10", "en": "10"}}, {"key": "d", "text": {"uz": "48", "ru": "48", "en": "48"}}]'::jsonb, 'b', 22),
  ((select id from public.directions where slug = 'math'), 2, '{"uz": "(−3)² = ?", "ru": "(−3)² = ?", "en": "(−3)² = ?"}'::jsonb, '[{"key": "a", "text": {"uz": "−9", "ru": "−9", "en": "−9"}}, {"key": "b", "text": {"uz": "9", "ru": "9", "en": "9"}}, {"key": "c", "text": {"uz": "6", "ru": "6", "en": "6"}}, {"key": "d", "text": {"uz": "−6", "ru": "−6", "en": "−6"}}]'::jsonb, 'b', 23),
  ((select id from public.directions where slug = 'math'), 2, '{"uz": "4, 8 va 12 sonlarining oʻrta arifmetigi:", "ru": "Среднее арифметическое чисел 4, 8 и 12:", "en": "The mean of 4, 8 and 12:"}'::jsonb, '[{"key": "a", "text": {"uz": "6", "ru": "6", "en": "6"}}, {"key": "b", "text": {"uz": "8", "ru": "8", "en": "8"}}, {"key": "c", "text": {"uz": "24", "ru": "24", "en": "24"}}, {"key": "d", "text": {"uz": "12", "ru": "12", "en": "12"}}]'::jsonb, 'b', 24),
  ((select id from public.directions where slug = 'math'), 3, '{"uz": "x² − 5x + 6 = 0 tenglamaning ildizlari:", "ru": "Корни уравнения x² − 5x + 6 = 0:", "en": "Roots of x² − 5x + 6 = 0:"}'::jsonb, '[{"key": "a", "text": {"uz": "1 va 6", "ru": "1 и 6", "en": "1 and 6"}}, {"key": "b", "text": {"uz": "2 va 3", "ru": "2 и 3", "en": "2 and 3"}}, {"key": "c", "text": {"uz": "−2 va −3", "ru": "−2 и −3", "en": "−2 and −3"}}, {"key": "d", "text": {"uz": "−1 va 6", "ru": "−1 и 6", "en": "−1 and 6"}}]'::jsonb, 'b', 30),
  ((select id from public.directions where slug = 'math'), 3, '{"uz": "log₂ 32 = ?", "ru": "log₂ 32 = ?", "en": "log₂ 32 = ?"}'::jsonb, '[{"key": "a", "text": {"uz": "4", "ru": "4", "en": "4"}}, {"key": "b", "text": {"uz": "5", "ru": "5", "en": "5"}}, {"key": "c", "text": {"uz": "6", "ru": "6", "en": "6"}}, {"key": "d", "text": {"uz": "16", "ru": "16", "en": "16"}}]'::jsonb, 'b', 31),
  ((select id from public.directions where slug = 'math'), 3, '{"uz": "Radiusi 3 boʻlgan doira yuzi:", "ru": "Площадь круга радиусом 3:", "en": "Area of a circle with radius 3:"}'::jsonb, '[{"key": "a", "text": {"uz": "6π", "ru": "6π", "en": "6π"}}, {"key": "b", "text": {"uz": "9π", "ru": "9π", "en": "9π"}}, {"key": "c", "text": {"uz": "3π", "ru": "3π", "en": "3π"}}, {"key": "d", "text": {"uz": "18π", "ru": "18π", "en": "18π"}}]'::jsonb, 'b', 32),
  ((select id from public.directions where slug = 'math'), 3, '{"uz": "sin 30° = ?", "ru": "sin 30° = ?", "en": "sin 30° = ?"}'::jsonb, '[{"key": "a", "text": {"uz": "1/2", "ru": "1/2", "en": "1/2"}}, {"key": "b", "text": {"uz": "√3/2", "ru": "√3/2", "en": "√3/2"}}, {"key": "c", "text": {"uz": "√2/2", "ru": "√2/2", "en": "√2/2"}}, {"key": "d", "text": {"uz": "1", "ru": "1", "en": "1"}}]'::jsonb, 'a', 33),
  ((select id from public.directions where slug = 'math'), 3, '{"uz": "3, 7, 11, … arifmetik progressiyaning 10-hadi:", "ru": "10-й член арифметической прогрессии 3, 7, 11, …:", "en": "The 10th term of the arithmetic sequence 3, 7, 11, …:"}'::jsonb, '[{"key": "a", "text": {"uz": "39", "ru": "39", "en": "39"}}, {"key": "b", "text": {"uz": "43", "ru": "43", "en": "43"}}, {"key": "c", "text": {"uz": "40", "ru": "40", "en": "40"}}, {"key": "d", "text": {"uz": "35", "ru": "35", "en": "35"}}]'::jsonb, 'a', 34),
  ((select id from public.directions where slug = 'math'), 4, '{"uz": "1 + 2 + 3 + … + 100 = ?", "ru": "1 + 2 + 3 + … + 100 = ?", "en": "1 + 2 + 3 + … + 100 = ?"}'::jsonb, '[{"key": "a", "text": {"uz": "5000", "ru": "5000", "en": "5000"}}, {"key": "b", "text": {"uz": "5050", "ru": "5050", "en": "5050"}}, {"key": "c", "text": {"uz": "5100", "ru": "5100", "en": "5100"}}, {"key": "d", "text": {"uz": "10100", "ru": "10100", "en": "10100"}}]'::jsonb, 'b', 40),
  ((select id from public.directions where slug = 'math'), 4, '{"uz": "Oltiburchakning nechta diagonali bor?", "ru": "Сколько диагоналей у шестиугольника?", "en": "How many diagonals does a hexagon have?"}'::jsonb, '[{"key": "a", "text": {"uz": "6", "ru": "6", "en": "6"}}, {"key": "b", "text": {"uz": "9", "ru": "9", "en": "9"}}, {"key": "c", "text": {"uz": "12", "ru": "12", "en": "12"}}, {"key": "d", "text": {"uz": "15", "ru": "15", "en": "15"}}]'::jsonb, 'b', 41),
  ((select id from public.directions where slug = 'math'), 4, '{"uz": "2²⁰²⁶ sonining oxirgi raqami:", "ru": "Последняя цифра числа 2²⁰²⁶:", "en": "The last digit of 2²⁰²⁶:"}'::jsonb, '[{"key": "a", "text": {"uz": "2", "ru": "2", "en": "2"}}, {"key": "b", "text": {"uz": "4", "ru": "4", "en": "4"}}, {"key": "c", "text": {"uz": "6", "ru": "6", "en": "6"}}, {"key": "d", "text": {"uz": "8", "ru": "8", "en": "8"}}]'::jsonb, 'b', 42),
  ((select id from public.directions where slug = 'math'), 4, '{"uz": "7 ga boʻlinadigan ikki xonali sonlar nechta?", "ru": "Сколько двузначных чисел делятся на 7?", "en": "How many two-digit numbers are divisible by 7?"}'::jsonb, '[{"key": "a", "text": {"uz": "12", "ru": "12", "en": "12"}}, {"key": "b", "text": {"uz": "13", "ru": "13", "en": "13"}}, {"key": "c", "text": {"uz": "14", "ru": "14", "en": "14"}}, {"key": "d", "text": {"uz": "15", "ru": "15", "en": "15"}}]'::jsonb, 'b', 43),
  ((select id from public.directions where slug = 'math'), 4, '{"uz": "a + b = 7 va ab = 12 boʻlsa, a² + b² = ?", "ru": "Если a + b = 7 и ab = 12, то a² + b² = ?", "en": "If a + b = 7 and ab = 12, then a² + b² = ?"}'::jsonb, '[{"key": "a", "text": {"uz": "25", "ru": "25", "en": "25"}}, {"key": "b", "text": {"uz": "37", "ru": "37", "en": "37"}}, {"key": "c", "text": {"uz": "49", "ru": "49", "en": "49"}}, {"key": "d", "text": {"uz": "24", "ru": "24", "en": "24"}}]'::jsonb, 'a', 44);

insert into public.test_questions (direction_id, level, question, options, correct_key, sort) values
  ((select id from public.directions where slug = 'it'), 1, '{"uz": "Boʻsh vaqtingizda nima qilishni yoqtirasiz?", "ru": "Чем вы любите заниматься в свободное время?", "en": "What do you enjoy doing in your free time?"}'::jsonb, '[{"key": "a", "text": {"uz": "Rasm chizish va chiroyli narsalar yaratish", "ru": "Рисовать и создавать красивые вещи", "en": "Drawing and creating beautiful things"}, "scores": {"design": 2}}, {"key": "b", "text": {"uz": "Mantiqiy jumboqlar yechish", "ru": "Решать логические головоломки", "en": "Solving logic puzzles"}, "scores": {"backend": 2}}, {"key": "c", "text": {"uz": "Sayt va ilovalar qanday koʻrinishini oʻzgartirish", "ru": "Менять, как выглядят сайты и приложения", "en": "Changing how websites and apps look"}, "scores": {"frontend": 2}}, {"key": "d", "text": {"uz": "Oʻyin oʻynash va ular qanday ishlashini bilish", "ru": "Играть в игры и разбираться, как они устроены", "en": "Playing games and figuring out how they work"}, "scores": {"python_kids": 2}}]'::jsonb, null, 1),
  ((select id from public.directions where slug = 'it'), 1, '{"uz": "Qaysi natija sizni koʻproq quvontiradi?", "ru": "Какой результат порадует вас больше?", "en": "Which result would make you happiest?"}'::jsonb, '[{"key": "a", "text": {"uz": "Hamma koʻradigan chiroyli sahifa", "ru": "Красивая страница, которую видят все", "en": "A beautiful page everyone can see"}, "scores": {"frontend": 2, "design": 1}}, {"key": "b", "text": {"uz": "Tez va xatosiz ishlaydigan tizim", "ru": "Система, которая работает быстро и без ошибок", "en": "A system that runs fast with no errors"}, "scores": {"backend": 2}}, {"key": "c", "text": {"uz": "Odamlarga yoqadigan logo yoki banner", "ru": "Логотип или баннер, который нравится людям", "en": "A logo or banner people love"}, "scores": {"design": 2}}, {"key": "d", "text": {"uz": "Oʻzim yasagan kichik oʻyin", "ru": "Маленькая игра, которую я сделал сам", "en": "A small game I built myself"}, "scores": {"python_kids": 2}}]'::jsonb, null, 2),
  ((select id from public.directions where slug = 'it'), 1, '{"uz": "Yoshingiz nechada?", "ru": "Сколько вам лет?", "en": "How old are you?"}'::jsonb, '[{"key": "a", "text": {"uz": "9–13", "ru": "9–13", "en": "9–13"}, "scores": {"python_kids": 3}}, {"key": "b", "text": {"uz": "14–17", "ru": "14–17", "en": "14–17"}, "scores": {"frontend": 1, "design": 1}}, {"key": "c", "text": {"uz": "18 va undan katta", "ru": "18 и старше", "en": "18 or older"}, "scores": {"frontend": 1, "backend": 1, "design": 1}}]'::jsonb, null, 3),
  ((select id from public.directions where slug = 'it'), 1, '{"uz": "Qaysi fan sizga osonroq?", "ru": "Какой предмет даётся вам легче?", "en": "Which subject comes easiest to you?"}'::jsonb, '[{"key": "a", "text": {"uz": "Matematika", "ru": "Математика", "en": "Math"}, "scores": {"backend": 2}}, {"key": "b", "text": {"uz": "Tasviriy sanʼat", "ru": "Изобразительное искусство", "en": "Art"}, "scores": {"design": 2}}, {"key": "c", "text": {"uz": "Informatika", "ru": "Информатика", "en": "Computer science"}, "scores": {"frontend": 1, "backend": 1}}, {"key": "d", "text": {"uz": "Hammasi qiziq, lekin oʻynab oʻrganishni yoqtiraman", "ru": "Всё интересно, но люблю учиться играя", "en": "Everything — but I like learning through play"}, "scores": {"python_kids": 2}}]'::jsonb, null, 4),
  ((select id from public.directions where slug = 'it'), 1, '{"uz": "Qanday ishlashni afzal koʻrasiz?", "ru": "Как вам больше нравится работать?", "en": "How do you prefer to work?"}'::jsonb, '[{"key": "a", "text": {"uz": "Natijani darhol ekranda koʻrish", "ru": "Сразу видеть результат на экране", "en": "Seeing the result on screen right away"}, "scores": {"frontend": 2}}, {"key": "b", "text": {"uz": "Koʻrinmasa ham, ichki mantiqni qurish", "ru": "Строить внутреннюю логику, даже если её не видно", "en": "Building the logic underneath, even if it is invisible"}, "scores": {"backend": 2}}, {"key": "c", "text": {"uz": "Rang, shrift va kompozitsiya bilan ishlash", "ru": "Работать с цветом, шрифтом и композицией", "en": "Working with colour, type and layout"}, "scores": {"design": 2}}, {"key": "d", "text": {"uz": "Qadam-baqadam, oʻyin orqali", "ru": "Шаг за шагом, через игру", "en": "Step by step, through play"}, "scores": {"python_kids": 2}}]'::jsonb, null, 5),
  ((select id from public.directions where slug = 'it'), 1, '{"uz": "Kelajakda kim boʻlishni xohlaysiz?", "ru": "Кем вы хотите стать в будущем?", "en": "What would you like to become?"}'::jsonb, '[{"key": "a", "text": {"uz": "Frontend dasturchi", "ru": "Frontend-разработчиком", "en": "A frontend developer"}, "scores": {"frontend": 3}}, {"key": "b", "text": {"uz": "Backend dasturchi", "ru": "Backend-разработчиком", "en": "A backend developer"}, "scores": {"backend": 3}}, {"key": "c", "text": {"uz": "UI/UX dizayner", "ru": "UI/UX-дизайнером", "en": "A UI/UX designer"}, "scores": {"design": 3}}, {"key": "d", "text": {"uz": "Hali bilmayman, sinab koʻrmoqchiman", "ru": "Пока не знаю, хочу попробовать", "en": "Not sure yet — I want to try"}, "scores": {"python_kids": 2}}]'::jsonb, null, 6);

insert into public.settings (key, value) values
  ('sla_minutes', '15'::jsonb),
  ('sla_escalation_minutes', '30'::jsonb),
  ('demo_mode', 'true'::jsonb),
  ('demo_reminder_24h_seconds', '30'::jsonb),
  ('demo_reminder_2h_seconds', '60'::jsonb),
  ('avg_study_months', '6'::jsonb),
  ('tg_group_chat_id', 'null'::jsonb)
on conflict (key) do nothing;

-- Guruhlar, slotlar, demo lidlar, bronlar va reklama xarajatlari — bugungi sanaga nisbatan.
select public.reset_demo_data();

commit;
